# Generated by Django 5.2.5 on 2025-08-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0003_remove_dynamicform_name_af_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicform",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="questiontype",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
