# Generated by Django 5.2.5 on 2025-08-07 15:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0004_dynamicform_slug_questiontype_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["page", "order"]},
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("serialized_form_data", models.JSONField()),
                ("is_published", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_by", models.CharField(blank=True, max_length=255)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="form_builder.dynamicform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Version",
                "verbose_name_plural": "Form Versions",
                "ordering": ["-version_number"],
                "unique_together": {("form", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answers", models.JSONField(blank=True, default=dict)),
                (
                    "user_session_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "started_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "created_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="form_builder.formversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "ordering": ["-created_datetime"],
            },
        ),
    ]
