# Generated by Django 5.2.5 on 2025-08-12 19:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0006_alter_question_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionGroupTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("address", "Address Block"),
                            ("contact", "Contact Information"),
                            ("name", "Name Fields"),
                            ("date_time", "Date and Time"),
                            ("custom", "Custom Group"),
                        ],
                        help_text="UI hint for rendering this group type",
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template configuration and default settings",
                    ),
                ),
                (
                    "question_template",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of question definitions to create when using this template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question Group Template",
                "verbose_name_plural": "Question Group Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="questiongroup",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Group-specific configuration and display settings",
            ),
        ),
        migrations.AlterField(
            model_name="questiongroup",
            name="display_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("address", "Address Block"),
                    ("contact", "Contact Information"),
                    ("name", "Name Fields"),
                    ("date_time", "Date and Time"),
                    ("custom", "Custom Group"),
                ],
                help_text="Hint for frontend rendering",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="questiongroup",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this group was created from (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="form_builder.questiongrouptemplate",
            ),
        ),
    ]
