# Generated by Django 5.2.5 on 2025-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "form_builder",
            "0007_questiongrouptemplate_alter_questiongroup_config_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="disabled_condition",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Condition that determines if this page should be disabled",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="disabled_condition",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Condition that determines if this question should be disabled",
            ),
        ),
    ]
