# Generated by Django 5.2.5 on 2025-08-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0008_page_disabled_condition_question_disabled_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="tag_display_condition",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Condition that determines when the tag should be displayed",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="tag_hover_text",
            field=models.TextField(
                blank=True,
                help_text="Text to show when hovering over the tag (e.g., 'Upgrading to premium allows for additional analysis')",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="tag_text",
            field=models.CharField(
                blank=True,
                help_text="Text to display in the tag/pill (e.g., 'Premium')",
                max_length=100,
            ),
        ),
    ]
