# Generated by Django 5.2.5 on 2025-08-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "form_builder",
            "0009_page_tag_display_condition_page_tag_hover_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="tag_link",
            field=models.URLField(
                blank=True,
                help_text="Optional URL to make the tag clickable",
                max_length=500,
            ),
        ),
    ]
